I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/chat.rpy", line 118, in script
    $ match_1 = matches[0]
  File "game/scripts/chat.rpy", line 118, in <module>
    $ match_1 = matches[0]
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/chat.rpy", line 118, in script
    $ match_1 = matches[0]
  File "/Users/aljo/Downloads/5y1s/psych 180/renpy-8.2.0-sdk/renpy/ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/aljo/Downloads/5y1s/psych 180/renpy-8.2.0-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/scripts/chat.rpy", line 118, in <module>
    $ match_1 = matches[0]
  File "/Users/aljo/Downloads/5y1s/psych 180/renpy-8.2.0-sdk/renpy/revertable.py", line 221, in __getitem__
    rv = list.__getitem__(self, index)
IndexError: list index out of range

macOS-15.0.1-arm64-arm-64bit arm64
Ren'Py 8.2.0.24012702
Simmer 1.0
Sun Nov  3 15:12:20 2024
