I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/profile.rpy", line 58, in script call
    call profile.repeat
  File "game/scripts/profile.rpy", line 26, in script
    $ player_profile.update(section_stats)
  File "game/scripts/profile.rpy", line 26, in <module>
    $ player_profile.update(section_stats)
ValueError: dictionary update sequence element #0 has length 1; 2 is required

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/profile.rpy", line 58, in script call
    call profile.repeat
  File "game/scripts/profile.rpy", line 26, in script
    $ player_profile.update(section_stats)
  File "/Users/aljo/Downloads/5y1s/psych 180/renpy-8.2.0-sdk/renpy/ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/aljo/Downloads/5y1s/psych 180/renpy-8.2.0-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/scripts/profile.rpy", line 26, in <module>
    $ player_profile.update(section_stats)
  File "/Users/aljo/Downloads/5y1s/psych 180/renpy-8.2.0-sdk/renpy/revertable.py", line 97, in do_mutation
    return method(self, *args, **kwargs)
ValueError: dictionary update sequence element #0 has length 1; 2 is required

macOS-15.0.1-arm64-arm-64bit arm64
Ren'Py 8.2.0.24012702
Simmer 1.0
Fri Nov  1 23:33:59 2024
